env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'next'
  - 'plugin:react-hooks/recommended'
  - 'plugin:import/recommended"'
  - 'prettier'
  - 'plugin:tailwindcss/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - 'react-hooks'
  - '@typescript-eslint'
rules:
  import/order:
    - error:
        alphabetize:
          order: asc
